baseurl: /date_data


collections:
    authors:
        output: true
defaults:
    - scope:
        path: ""
        type: "authors"
      values:
        layout: "author"
    - scope:
        path: ""
        type: "posts"
      values:
        layout: "post"
    - scope:
        path: "{{site.baseurl}}"
      values:
        layout: "default"
plugins:
    - jekyll-feed
    - jekyll-sitemap
    - jekyll-seo-tag
permalink: /:categories/:year/:month/:day/:title:output_ext


